name: 'staging'

on:
  workflow_run:
    workflows: ['lint and tests']
    branches: [main]
    types:
      - completed
  workflow_dispatch:

env:
  KEYSTORE_PW: ${{ secrets.KEYSTORE_PW }}
  KEYSTORE:    ${{ secrets.KEYSTORE }}
  SA_JSON_KEY: ${{ secrets.SA_JSON_KEY }}
  ALIAS:       ${{ secrets.ALIAS }}
  ALIAS_PW:    ${{ secrets.ALIAS_PW }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
  APP_VERSION_NAME: ${{ secrets.APP_VERSION_NAME }}

jobs:
  staging_firebase:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v3
      - run: |
              echo $KEYSTORE | base64 -d -i > /tmp/my-release-key.keystore
              echo $SA_JSON_KEY | base64 -d -i > key_firebase.json
              echo $GOOGLE_SERVICES_JSON | base64 -d -i > app/google-services.json
              bundle exec fastlane firebase_distribution
        env:
          FIREBASE_APP_ID:  ${{ secrets.FIREBASE_APP_ID_STG }}
          BUILD_TASK: "assemble"
          BUILD_TYPE: "debug"